# Generated by Django 3.1.6 on 2021-04-29 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0002_auto_20210429_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, default='',on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='auth.user'),
        ),
    ]
